import Head from "next/head";
import SectionHomePageSearch from "@/components/SectionHomePageSearch";
import SectionCard from "@/components/SectionCard";
import SectionCoupon from "@/components/SectionCoupon";
import CarouselHome from './../components/CarouselHome';

const images = [
  {
    id: 1,
    src: "/zSmile-together.avif",
  },
  {
    id: 2,
    src: "/sKickoff-CM4.webp",
  },
  {
    id: 3,
    src: "/bannersinh_nhat_4-desk.webp",
  }
];
export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CarouselHome images={images} />
        <SectionHomePageSearch />
        <SectionCard />
        <SectionCoupon />
      </main>
    </>
  );
}
